# Generated by Django 4.1.1 on 2022-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField(blank=True)),
                ('date', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=300)),
                ('goupu', models.CharField(blank=True, max_length=300, null=True)),
                ('duration', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
