# Generated by Django 4.1.1 on 2022-09-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventregister_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='goupu',
            new_name='group',
        ),
    ]
